### ISSUE TITLE
Python Error 3.36.2

### ISSUE THREAD

**Issue by FlyingEagle** [Kanahiro/EZPrinter#8]
I got this message since 
QGIS version
3.36.2-Maidenhead

```
2024-07-16T17:00:42     WARNING    Traceback (most recent call last):
              File "C:\Users/%%USERNAME%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ezprinter\ezprinter.py", line 274, in initClicktool
              self.apllyGuiValuesToClickTool()
              File "C:\Users/%%USERNAME%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ezprinter\ezprinter.py", line 286, in apllyGuiValuesToClickTool
              ct = ClickTool(self.iface, self.mapCanvasClicked, paperSize, printScale, horizontal, widemode)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/%%USERNAME%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ezprinter\clickTool.py", line 23, in __init__
              self.reloadCursorRectangle()
              File "C:\Users/%%USERNAME%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ezprinter\clickTool.py", line 27, in reloadCursorRectangle
              self.setCursor(QCursor(self.makeRectCursor()))
              ^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/%%USERNAME%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ezprinter\clickTool.py", line 65, in makeRectCursor
              image = QImage(QSize(width, height), QImage.Format_ARGB32)
              ^^^^^^^^^^^^^^^^^^^^
             TypeError: arguments did not match any overloaded call:
              QSize(): too many arguments
              QSize(w: int, h: int): argument 1 has unexpected type 'float'
              QSize(a0: QSize): argument 1 has unexpected type 'float'
```

**Comment by alanscandrett** [comment]
Still the same issue for 3.40.12-Bratislava
